### ISSUE TITLE
Homebridge can't start when device ist not available

### ISSUE THREAD

**Issue by Tom2Drake** [rchrch/homebridge-mhacwifi1-lan#1] opened 2021-05-12 16:48 UTC
When Homebridge and the AirCon is noch available Homebridge can't start.

[12/05/2021, 18:46:41] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-mhacwifi1-lan/src/accessories/device.ts:380:41)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[12/05/2021, 18:46:41] [Air Conditioning] No device found at address: 192.168.178.26 ([object Object])

**Comment by rchrch** [comment] 2022-10-02 01:43
Sorry for the very late response. I haven't had any time for this project.

I can't reproduce this problem.  With an incorrect IP address, homebridge continues to run for me (of course with errors saying no device is available).  Here is a log except with a bad IP address:

```
[02/10/2022, 11:09:35 am] Homebridge v1.5.0 (HAP v0.10.4) (Homebridge) is running on port 51826.
[02/10/2022, 11:09:36 am] [Homebridge UI] Homebridge Config UI X v4.50.1 is listening on :: port 8080
[02/10/2022, 11:09:38 am] [homebridge-mhacwifi1-lan] Http request error: Error: connect EHOSTUNREACH 10.0.20.209:80
[02/10/2022, 11:09:38 am] [homebridge-mhacwifi1-lan] No device found at address: 10.0.20.209 (Error: connect EHOSTUNREACH 10.0.20.209:80)
[02/10/2022, 11:09:48 am] [homebridge-mhacwifi1-lan] Checking for device at 10.0.20.209
...
[02/10/2022, 11:09:51 am] [homebridge-mhacwifi1-lan] Http request error: Error: connect EHOSTUNREACH 10.0.20.209:80
[02/10/2022, 11:09:51 am] [homebridge-mhacwifi1-lan] No device found at address: 10.0.20.209 (Error: connect EHOSTUNREACH 10.0.20.209:80)
[02/10/2022, 11:10:01 am] [homebridge-mhacwifi1-lan] Checking for device at 10.0.20.209
...
more of the same
```

I don't see a JSON error in my logs.  Was that possibly the problem?

**Comment by rchrch** [comment] 2022-10-20 08:42
If you are still having trouble, please let me know. Otherwise I will close this issue.

**Closed** 2022-11-01 09:27 UTC
